# Generated by Django 3.2.4 on 2021-06-17 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_rename_title_artist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='cover',
            new_name='picture',
        ),
    ]
