# Generated by Django 3.2.4 on 2021-06-17 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_rename_cover_artist_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='name',
            new_name='title',
        ),
    ]
